// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIgyStGRPHmAQegOkMsuS7mlLK8MlnzMw',
    appId: '1:135217251215:web:44ea8639f6e8972fe881fa',
    messagingSenderId: '135217251215',
    projectId: 'investech-3836a',
    authDomain: 'investech-3836a.firebaseapp.com',
    storageBucket: 'investech-3836a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5LhLWx0Fb7-5CjydcNJC5TWK_ok0H95U',
    appId: '1:135217251215:android:f01f203a266fe23ce881fa',
    messagingSenderId: '135217251215',
    projectId: 'investech-3836a',
    storageBucket: 'investech-3836a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDf8erjqQPyaFCT2bGgVDPFos8DXBoGU0',
    appId: '1:135217251215:ios:e0ec7a673507c202e881fa',
    messagingSenderId: '135217251215',
    projectId: 'investech-3836a',
    storageBucket: 'investech-3836a.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalInvestechRubenMendozaMayo2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDf8erjqQPyaFCT2bGgVDPFos8DXBoGU0',
    appId: '1:135217251215:ios:e0ec7a673507c202e881fa',
    messagingSenderId: '135217251215',
    projectId: 'investech-3836a',
    storageBucket: 'investech-3836a.firebasestorage.app',
    iosBundleId: 'com.example.proyectoFinalInvestechRubenMendozaMayo2026',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIgyStGRPHmAQegOkMsuS7mlLK8MlnzMw',
    appId: '1:135217251215:web:0160cfbc381c869de881fa',
    messagingSenderId: '135217251215',
    projectId: 'investech-3836a',
    authDomain: 'investech-3836a.firebaseapp.com',
    storageBucket: 'investech-3836a.firebasestorage.app',
  );
}
